esphome:
  name: seeed_xiao_esp32s3
  friendly_name: seeed_xiao_esp32s3

esp32:
  board: seeed_xiao_esp32s3
  flash_size: 8MB
  cpu_frequency: 240MHz
  framework:
    type: esp-idf
    sdkconfig_options:
      CONFIG_ESP32S3_DEFAULT_CPU_FREQ_240: "y"
      CONFIG_ESP32S3_DATA_CACHE_64KB: "y"
      CONFIG_ESP32S3_DATA_CACHE_LINE_64B: "y"

psram:
  mode: octal
  speed: 80MHz

http_request:
  useragent: esphome/device
  timeout: 10s
  verify_ssl: false
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

# Home Assistant API - 必需用于集成
api:

# OTA 更新
ota:
  platform: esphome

# 启用日志
logger:

# I2C总线
i2c:
  - id: camera_i2c
    sda: GPIO40
    scl: GPIO39
    frequency: 100kHz
    scan: false

esp32_camera:
  name: My Camera
  external_clock:
    pin: GPIO10           # XCLK_GPIO_NUM
    frequency: 20MHz
  i2c_id: camera_i2c
  data_pins: [GPIO15, GPIO17, GPIO18, GPIO16, GPIO14, GPIO12, GPIO11, GPIO48]
  vsync_pin: GPIO38
  href_pin: GPIO47
  pixel_clock_pin: GPIO13 # PCLK_GPIO_NUM
  # power_down_pin: -1    # PWDN_GPIO_NUM (未使用)
  # reset_pin: -1         # RESET_GPIO_NUM (未使用)
  resolution: 320x240     # QVGA - 分辨率
  jpeg_quality: 15        # 适合高分辨率的质量设置 (10=最高质量, 63=最低质量)
  horizontal_mirror: true # 左右翻转图像(无效)
  # 图像调整参数 - 改善亮度
  brightness: 1           # 亮度调整 (-2 到 2, 默认0)
  contrast: 1             # 对比度调整 (-2 到 2, 默认0)
  saturation: 0           # 饱和度调整 (-2 到 2, 默认0)
  # 自动曝光和增益控制
  aec_mode: auto          # 自动曝光控制
  aec2: true              # 启用高级自动曝光
  ae_level: 1             # 自动曝光级别 (-2 到 2, 默认0)
  agc_mode: auto          # 自动增益控制
  agc_gain_ceiling: 16x   # 增益上限 (2x, 4x, 8x, 16x, 32x, 64x, 128x)
  wb_mode: auto           # 自动白平衡
  


