---
packages:
  m5-tab5: !include m5-tab5.yaml

esphome:
  project:
    name: esphome.voice-assistant
    version: dev

ota:
  - platform: esphome

wifi:
  on_connect:
    - delay: 5s
    # - ble.disable:
  on_disconnect:
    # - ble.enable:
