---
packages:
  m5-tab5: !include m5-tab5-test1.yaml

esphome:
  project:
    name: esphome.voice-assistant
    version: dev

ota:
  - platform: esphome

wifi:
  on_connect:
    - delay: 5s
  on_disconnect:
