esphome:
  name: m5-tab5-test
  friendly_name: m5-tab5-test
  min_version: 2025.9.3      # 要求的最低ESPHome版本
  name_add_mac_suffix: true  # 设备名后缀添加MAC地址，避免冲突

esp32:
  variant: esp32p4
  board: m5stack-tab5-p4
  flash_size: 16MB
  engineering_sample: true
  cpu_frequency: 360MHz
  framework:
    type: esp-idf
    sdkconfig_options:
      CONFIG_LWIP_TCP_WND_DEFAULT: "16384"
      CONFIG_SPI_FLASH_YIELD_DURING_ERASE: "y"

# WiFi模块配置（ESP32-C6）
esp32_hosted:
  variant: esp32c6
  active_high: true
  clk_pin: GPIO12
  cmd_pin: GPIO13
  d0_pin: GPIO11
  d1_pin: GPIO10
  d2_pin: GPIO9
  d3_pin: GPIO8
  reset_pin: GPIO15
  slot: 1

psram:
  mode: hex
  speed: 200MHz

ota:
  - platform: esphome
    id: ota_esphome

logger:
  hardware_uart: USB_SERIAL_JTAG

wifi:
  ap:

captive_portal:

# 屏幕背光控制 (GPIO47)
output:
  - platform: ledc
    pin: GPIO22
    id: backlight_output

light:
  - platform: monochromatic
    id: led
    name: Screen
    icon: "mdi:television"
    entity_category: config
    output: backlight_output
    restore_mode: RESTORE_DEFAULT_ON
    default_transition_length: 250ms

# I2C总线
i2c:
  - id: bsp_bus
    sda: GPIO31
    scl: GPIO32
    frequency: 400kHz

pi4ioe5v6408:
  - id: pi4ioe1
    address: 0x43
  - id: pi4ioe2
    address: 0x44

esp_ldo:
  - voltage: 2.5V
    channel: 3


# 字体 (Fonts): 使用Google Fonts下载Noto Sans SC字体，并预渲染指定字符
font:
  - file:
      type: gfonts
      family: "Noto Sans SC"
      weight: 400
      italic: false
    id: font_request  # 用于显示用户请求文本
    size: 15
    glyphs: ${allowed_characters}
    ignore_missing_glyphs: true


# 显示屏 (Display): 配置ILI9XXX系列屏幕（S3BOX型号）
display:
  - platform: mipi_dsi
    dimensions:
      height: 1280
      width: 720
    id: p4_box_lcd
    model: M5STACK-TAB5-V2
    reset_pin:
      pi4ioe5v6408: pi4ioe1
      number: 4
    pixel_mode: 16bit
    color_order: RGB
    update_interval: never
    # 定义了多个显示页面，每个页面是一个独立的绘制函数
    pages:
      # 空闲页面
      - id: idle_page
        lambda: |-
          it.fill(id(idle_color));
          it.image((it.get_width() / 2), (it.get_height() / 2), id(casita_idle), ImageAlign::CENTER);
          id(draw_timer_timeline).execute();
          id(draw_active_timer_widget).execute();

