esphome:
  name: lc-szpi-esp32s3
  friendly_name: lc-szpi-esp32s3

esp32:
  board: esp32-s3-devkitc-1
  flash_size: 16MB
  cpu_frequency: 240MHz
  framework:
    type: esp-idf
    sdkconfig_options:
      CONFIG_ESP32S3_DEFAULT_CPU_FREQ_240: "y"
      CONFIG_ESP32S3_DATA_CACHE_64KB: "y"
      CONFIG_ESP32S3_DATA_CACHE_LINE_64B: "y"

# 启用日志
logger:

i2c:
  - id: bus_a
    sda: 1
    scl: 2
    scan: true

pca9554:
  - id: pca9557
    address: 0x19

# 屏幕背光控制 (GPIO2)
output:
  - platform: ledc
    pin: 42
    id: backlight_output
    inverted: true

light:
  - platform: monochromatic
    id: Sled
    name: Screen
    icon: "mdi:television"
    entity_category: config
    output: backlight_output
    restore_mode: ALWAYS_ON
    default_transition_length: 250ms

# 图像资源 (Images): 从URL下载并缓存到设备Flash中
image:
  - file: https://github.com/pysn2012/wake-word-voice-assistants/raw/main/casita/listening_240_320.png
    id: casita_listening
    resize: 240x320
    type: RGB
    transparency: alpha_channel

color:
  - id: my_red
    red: 100%
    green: 0%
    blue: 0%

# SPI总线配置
spi:
  id: spi_bus
  clk_pin: GPIO41
  mosi_pin: GPIO40

switch:
  - platform: gpio
    id: lcd_en
    name: "LCD EN (PCA bit0)"
    pin:
      pca9554: pca9557
      number: 0
      mode: { output: true }
      inverted: true
    restore_mode: ALWAYS_ON 

# 屏幕配置
display:
  - platform: mipi_spi
    id: main_display
    model: ST7789V
    dc_pin: GPIO39
    invert_colors: true

    lambda: |-
      it.image((it.get_width() / 2), (it.get_height() / 2), id(casita_listening), ImageAlign::CENTER);
      it.print(0, 0, id(Roboto_font), "Hello World!");

font:
  - file: "gfonts://Roboto"
    id: Roboto_font
    size: 20