esphome:
  name: unihiker-k10
  friendly_name: Unihiker-k10

esp32:
  board: esp32-s3-devkitc-1
  flash_size: 16MB
  cpu_frequency: 240MHz
  framework:
    type: esp-idf
    sdkconfig_options:
      CONFIG_ESP32S3_DEFAULT_CPU_FREQ_240: "y"
      CONFIG_ESP32S3_DATA_CACHE_64KB: "y"
      CONFIG_ESP32S3_DATA_CACHE_LINE_64B: "y"

psram:
  mode: octal
  speed: 80MHz

# 启用日志
logger:

# I2C总线
i2c:
  id: i2c_a
  scl: GPIO48
  sda: GPIO47
  frequency: 100kHz
  scan: false

# XL9535 I/O 扩展器配置
xl9535:
  - id: xl9535_hub
    address: 0x20
    i2c_id: i2c_a

# 背光输出：使用 XL9535 的 Pin 0
output:
  - platform: gpio
    id: screen_backlight
    pin:
      xl9535: xl9535_hub
      number: 0          # 对应 P0
      mode: OUTPUT       # 必须设为输出
      inverted: false    # 非反转：写 HIGH = 开启背光

# 开关
switch:
  # 背光开关
  - platform: output
    name: "Screen Backlight"
    output: screen_backlight
    restore_mode: ALWAYS_ON  # 启动时自动开启背光

# 二进制传感器：按键A和B
binary_sensor:
  # 按键A - XL9535 P14，配置为GPIO输入
  - platform: gpio
    id: button_a
    name: "Button A"
    pin:
      xl9535: xl9535_hub  # 引用你之前定义的xl9535组件
      number: 14          # 引脚号 P14
      mode: INPUT         # 设置为输入模式
      inverted: true      # 通常按键按下时为低电平，建议使用反转
    on_press:
      - lambda: id(display_text) = "AAAAA";
      - logger.log: "Button A pressed"
      - component.update: k10_lcd
    on_release:
      - logger.log: "Button A released"
  
  # 按键B - XL9535 P02，配置方法相同
  - platform: gpio
    id: button_b
    name: "Button B"
    pin:
      xl9535: xl9535_hub
      number: 2
      mode: INPUT
      inverted: true
    on_press:
      - lambda: id(display_text) = "BBBBB";
      - logger.log: "Button B pressed"
      - component.update: k10_lcd
    on_release:
      - logger.log: "Button B released"

# 图像资源 (Images): 从URL下载并缓存到设备Flash中
image:
  - file: https://github.com/pysn2012/wake-word-voice-assistants/raw/main/casita/listening_240_320.png
    id: casita_listening
    resize: 240x320
    type: RGB
    transparency: alpha_channel

# 字体 (Fonts): 使用Google Fonts下载Noto Sans SC字体，并预渲染指定字符
font:
  - file:
      type: gfonts
      family: "Noto Sans SC"
      weight: 400
      italic: false
    id: font_main
    size: 24
    glyphs: |-
      abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890~`!$^()_[]\;:'",<.>?
    ignore_missing_glyphs: true

color:
  - id: white_color
    hex: "FFFFFF"
  - id: black_color
    hex: "000000"
  - id: red_color
    hex: "FF0000"
  - id: blue_color
    hex: "0000FF"
  - id: green_color
    hex: "00FF00"

# SPI总线配置（在此处设置SPI速度）
spi:
  id: spi_bus  # 定义SPI总线ID，供显示屏引用
  clk_pin: GPIO12
  mosi_pin: GPIO21
  interface: spi2

# 屏幕配置（修正平台参数）
display:
  - platform: ili9xxx
    model: ILI9341
    cs_pin: GPIO14
    dc_pin: GPIO13
    spi_id: spi_bus
    invert_colors: false
    show_test_card: false
    dimensions:
      width: 240
      height: 320
    transform:
      mirror_x: false
      mirror_y: true
    update_interval: 100ms

    # 显示文字
    lambda: |-
      // 清屏
      it.fill(id(black_color));
      
      // 只在有按键按下时显示文字
      if (id(button_a).state) {
        // 按下A键：显示A键文字
        it.printf(0, 80, id(font_main), id(white_color), "%s", id(display_text).state.c_str());
      } else if (id(button_b).state) {
        // 按下B键：显示B键文字
        it.printf(0, 80, id(font_main), id(white_color), "%s", id(display_text).state.c_str());
      }
