---
packages:
  # This is an inline package to prefix the on_client_connected with the wait_until action
  # It must appear before the actual package so it becomes the orignal config and the
  # on_client_connected list from the package config is appends onto this one.
  va_connected_wait_for_ble:
    voice_assistant:
      on_client_connected:
        - wait_until:
            not: ble.enabled
  esp32-s3-box-3: !include unihiker-k10.yaml

esphome:
  project:
    name: esphome.voice-assistant
    version: dev

ota:
  - platform: http_request
    id: ota_http_request

http_request:

dashboard_import:
  package_import_url: github://pysn2012/wake-word-voice-assistants/unihiker-k10/unihiker-k10.yaml@main

wifi:
  on_connect:
    - delay: 5s  # Gives time for improv results to be transmitted
    - ble.disable:
  on_disconnect:
    - ble.enable:

improv_serial:

esp32_improv:
  authorizer: none
